# Network
server=1
listen=0
noupnp=1
maxconnections=16
daemon=0

# RPC
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=8888
rpcuser=user
rpcpassword=password

# Indexes
txindex=1
addressindex=1
spentindex=1
timestampindex=1
coinstatsindex=1
mobile=1

# ZMQ
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubrawblock=tcp://127.0.0.1:28333
zmqpubhashtx=tcp://127.0.0.1:28334
zmqpubhashblock=tcp://127.0.0.1:28335
