export type { FiroRpcClient } from './utils/client.js';
export { createFiroRpcClient } from './utils/client.js';
export { RpcCallError } from './utils/rpc.js';

export type {
  // RPC core
  RpcConfig,
  RpcRequest,
  RpcResponse,
  RpcError,
  BatchCall,
  BatchResult,
  // Firo types
  Block,
  BlockchainInfo,
  Bip9SoftFork,
  SoftFork,
  ChainTip,
  ChainTipStatus,
  MempoolAncestorsResult,
  MempoolDescendantsResult,
  SpecialTxesResult,
  Transaction,
  TxType,
  Vin,
  CoinbaseVin,
  StandardVin,
  SparkSpendVin,
  Vout,
  ScriptSig,
  ScriptPubKey,
  CbTx,
  ProUpServTx,
  FinalCommitment,
  QuorumCommitment,
  RawTxInput,
  RawTxOutput,
  PrevTx,
  SignRawTransactionResult,
  DecodeRawTransactionResult,
  DecodeScriptResult,
  FundRawTransactionResult,
  TxOutSetInfo,
  NetworkInfo,
  PeerInfo,
  MempoolInfo,
  MempoolEntry,
  RawMempool,
  FiroAddressBalance,
  FiroAddressTxIds,
  AddressDelta,
  AddressMempoolDelta,
  AddressUtxo,
  SpentInfo,
  TotalSupply,
  BlockHeader,
  TxOut,
  // Wallet
  WalletInfo,
  ValidateAddressResult,
  WalletTxCategory,
  WalletTransactionDetail,
  WalletTransaction,
  WalletTransactionListEntry,
  ListSinceBlockResult,
  UnspentOutput,
  UsedCoinsTags,
  AddressGroupingEntry,
  AddressGrouping,
  AddressBalances,
  LockedUnspent,
  ReceivedByAddressEntry,
  SendTransparentRecipientOptions,
  SendTransparentRecipients,
  BumpFeeOptions,
  BumpFeeResult,
  UnspentOutputRef,
  ImportMultiRequest,
  ImportMultiOptions,
  ImportMultiResult,
  // Spark
  SparkAnonymitySet,
  SparkAnonymitySetMeta,
  SparkAnonymitySetSector,
  SparkAnonymitySetCoin,
  SparkName,
  SparkNameData,
  SparkRecipient,
  SparkSendRecipients,
  SparkAddressBalance,
  SparkAddresses,
  SparkMint,
  SparkSpend,
  UnspentSparkMint,
  IdentifySparkCoinsResult,
  SparkCoinAddress,
  SparkMintRecipient,
  SparkMintRecipients,
  MempoolSparkTxs,
  // Fees
  FeeRate,
  SmartFeeEstimate,
  SmartPriorityEstimate,
  // Evo
  ProTxList,
  ProTxState,
  ProTxWallet,
  ProTxInfo,
  ProTxDiffMNListEntry,
  ProTxDiffQuorumRef,
  ProTxDiffNewQuorum,
  ProTxDiff,
  QuorumList,
  QuorumMember,
  QuorumInfo,
  QuorumMinableCommitment,
  QuorumDkgStatus,
  QuorumMembership,
  QuorumMemberOf,
  QuorumRecoveredSig,
  EvozNodeInfo,
  EvozNodeList,
  EvozNodeCount,
  EvozNodeHeightInfo,
  EvozNodeWinners,
  BlsKeyPair,
  SporkList,
  EvozNodeSyncStatus,
  // Util
  MultisigResult,
} from './types/index.js';
