export type { FiroRpcClient } from './utils/client.js';
export { createFiroRpcClient } from './utils/client.js';
export { RpcCallError } from './utils/rpc.js';

export type {
  // RPC core
  RpcConfig,
  RpcRequest,
  RpcResponse,
  RpcError,
  BatchCall,
  BatchResult,
  // Firo types
  Block,
  BlockchainInfo,
  Bip9SoftFork,
  SoftFork,
  ChainTip,
  ChainTipStatus,
  MempoolAncestorsResult,
  MempoolDescendantsResult,
  SpecialTxesResult,
  Transaction,
  TxType,
  Vin,
  CoinbaseVin,
  StandardVin,
  SparkSpendVin,
  Vout,
  ScriptSig,
  ScriptPubKey,
  CbTx,
  ProUpServTx,
  FinalCommitment,
  QuorumCommitment,
  TxOutSetInfo,
  NetworkInfo,
  PeerInfo,
  MempoolInfo,
  MempoolEntry,
  RawMempool,
  FiroAddressBalance,
  FiroAddressTxIds,
  // Blockchain (extended)
  BlockHeader,
  TxOut,
  // Wallet
  WalletInfo,
  ValidateAddressResult,
  WalletTransaction,
  WalletTransactionListEntry,
  ListSinceBlockResult,
  UnspentOutput,
  UsedCoinsTags,
  // Spark
  SparkAnonymitySet,
  SparkAnonymitySetMeta,
  SparkAnonymitySetSector,
  SparkAnonymitySetCoin,
  SparkName,
  SparkNameData,
  SparkRecipient,
  SparkSendRecipients,
  SparkAddressBalance,
  SparkAddresses,
  SparkMint,
  SparkSpend,
  UnspentSparkMint,
  IdentifySparkCoinsResult,
  SparkCoinAddress,
  SparkMintRecipient,
  SparkMintRecipients,
  MempoolSparkTxs,
  // Fees
  FeeRate,
  SmartFeeEstimate,
  SmartPriorityEstimate,
  // Evo
  ProTxList,
  ProTxState,
  ProTxWallet,
  ProTxInfo,
  ProTxDiffMNListEntry,
  ProTxDiffQuorumRef,
  ProTxDiffNewQuorum,
  ProTxDiff,
  QuorumList,
  QuorumMember,
  QuorumInfo,
  QuorumMinableCommitment,
  QuorumDkgStatus,
  QuorumMembership,
  QuorumMemberOf,
  QuorumRecoveredSig,
} from './types/index.js';
